name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH(원격 접속)로 EC2에 접속하기
        # 사용하는 라이브러리
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USERNAME}}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/ubuntu/github-actions-practice
            git pull origin main
            ./gradlew clean build -x test
            sudo fuser -k -n tcp 8080 || true
            cp build/libs/*SNAPSHOT.war /opt/tomcat9/webapps/ROOT.war
            nohup /opt/tomcat9/bin/startup.sh > ./tomcat.log 2>&1 &
            
